#ifndef LIBVEHRECDLL_GLOBAL_H
#define LIBVEHRECDLL_GLOBAL_H

//#include <QtCore/qglobal.h>

#if defined(LIBVEHRECDLL_LIBRARY)
#  define LIBVEHRECDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBVEHRECDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBVEHRECDLL_GLOBAL_H
